prooph_service_bus:
    command_buses:
        default_command_bus: ~
    event_buses:
        default_event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                type: 'prooph_service_bus.event_bus_router'
                routes:
                    'App\Domain\Author\Events\AuthorWasCreated':
                        - '@App\Infrastructure\Author\Projection\AuthorReadModel'
    query_buses:
        default_query_bus: ~

services:
    _defaults:
        public: false

    Prooph\ServiceBus\CommandBus: '@prooph_service_bus.default_command_bus'
